export const userSchema = {
  first_name: ``,
  secondary_name: ``,
  lastname: ``,
  second_lastname: ``,
  email: ``,
  phone: ``,
  birthday: ``,
  street_address: ``,
  city: ``,
  state: ``,
  zipcode: ``,
  insurance_date: ``,
  insurance_policy_number: ``,
  insurance_company: ``,
  plan: ``,
  notes: ``,
  sms_chat_service_sid: ``,
  whatsapp_chat_service_sid: ``,
  sms_sid: ``,
  whatsapp_sid: ``,
  chat_mode: `sms`,
  identity: ``,
};
